---
# Loading vars
- name: Add the OS specific varibles
  include_vars: "Debian.yml"

# Install DHCP server
- name: Install the required packages in Debian derivatives
  apt: name={{ ntp_server_package }}
       state=present
       update_cache=yes

# Generate configuration
- name: Generate chrony.conf
  template:
    src=chrony.conf.j2
    dest={{ ntp_server_config }}
    owner=root
    group=root
    mode=0644
  notify:
    - restart ntp
