---
- name: 'Kea dhcp4 restart'
  ansible.builtin.service:
    name: '{{ kea_dhcp4_svc }}'
    state: 'restarted'
  when: kea_svc_restart

- name: 'Kea dhcp4 reload'
  ansible.builtin.service:
    name: '{{ kea_dhcp4_svc }}'
    state: 'reloaded'
  when: kea_svc_restart

- name: 'Kea dhcp6 restart'
  ansible.builtin.service:
    name: '{{ kea_dhcp6_svc }}'
    state: 'restarted'
  when: kea_svc_restart

- name: 'Kea dhcp6 reload'
  ansible.builtin.service:
    name: '{{ kea_dhcp6_svc }}'
    state: 'reloaded'
  when: kea_svc_restart

- name: 'Kea ddns restart'
  ansible.builtin.service:
    name: '{{ kea_ddns_svc }}'
    state: 'restarted'
  when: kea_svc_restart

- name: 'Kea ddns reload'
  ansible.builtin.service:
    name: '{{ kea_ddns_svc }}'
    state: 'reloaded'
  when: kea_svc_restart

- name: 'Kea ctrl agent restart'
  ansible.builtin.service:
    name: '{{ kea_ctrl_agent_svc }}'
    state: 'restarted'
  when: kea_svc_restart

- name: 'Kea ctrl agent reload'
  ansible.builtin.service:
    name: '{{ kea_ctrl_agent_svc }}'
    state: 'reloaded'
  when: kea_svc_restart

# FreeBSD uses one service, which just wraps keactrl which in turn reads
# /usr/local/etc/keactrl.conf
- name: 'Kea reload'
  ansible.builtin.service:
    name: 'kea'
    state: 'reloaded'
  when: kea_svc_restart

- name: 'Kea restart'
  ansible.builtin.service:
    name: 'kea'
    state: 'restarted'
  when: kea_svc_restart
