---
- hosts: manager
  gather_facts: yes
  become: True

  pre_tasks:
     - name: Using IP address
       ansible.builtin.debug:
         msg: System {{ subnet.ip }}

     - name: Distribution
       debug: msg="{{ ansible_distribution }}"

     - name: Distribution version
       debug: msg="{{ ansible_distribution_version}}"

     - name: Distribution major version
       debug: msg="{{ ansible_distribution_major_version }}"

  roles:
    - common
    - network
    - sudo
    - dhcp-server
    - nginx
    - manager
