manager:
  hosts:
      manager.local 
  vars:
      hostname: Manager
      ansible_user: pi

cache:
  hosts:
       cache.local 
  vars:
       hostname: Cache
       ansible_user: pi

prometheus:
  hosts:
       prometheus.local 
  vars:
       hostname: Prometheus
       ansible_user: pi

windows:
  hosts: 
       192.168.1.22:
  vars:
       ansible_user: steve
       ansible_connection: ssh
       ansible_ssh_private_key_file: ~/.ssh/ansible
       ansible_remote_tmp: /temp
       ansible_shell_type: powershell
       shell_type: powershell
       ansible_python_interpreter: c:\Python311\python
