---
- name: Install proxy packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ proxy_packages }}"
  tags: setup

- name: Enable/disable DHCP4 service
  ansible.builtin.service:
    name: "{{ proxy_svc }}"
    enabled: "{{ proxy_enable }}"
  tags: setup

- name: Install dhcp4 configuration
  ansible.builtin.template:
    src: "squid.conf.j2"
    dest: "{{ proxy_config_path }}/squid.conf"
    mode: "0640"
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
  when: proxy_enable
  notify:
    - 'proxy reload'
  tags: configuration

- name: Make sure proxy is running (if first setup)
  ansible.builtin.service:
    name: "{{ proxy_svc }}"
    state: started
  when: proxy_enable
