manager:
   ip: 192.168.10.1
   interface: eth0
   web:
      directory: /home/manager
      package: https://api.github.com/repos/sfawcett123/fsm/releases/latest
        

configure_apparmor: true

proxy:
  port: 3128

subnet:
  cidr: 192.168.10.0/24
  range:
    from: 192.168.10.100
    to: 192.168.10.200
  options:
     subnet_mask: 255.255.255.0
     broadcast_address: 192.168.10.255
     domain_name_servers: 192.168.10.1
     domain_name: "flightsim.lan"
