manager:
   ip: 192.168.10.1
   interface: eth0

configure_apparmor: true

proxy:
  port: 3128

subnet:
  cidr: 192.168.10.0/24
  range:
    from: 192.168.10.100
    to: 192.168.10.200
  options:
     subnet-mask: 255.255.255.0
     broadcast-address: 192.168.10.255
     domain-name-servers: 192.168.10.1
     domain-name: "flightsim.lan"
