---
galaxy_info:
  author: "Oscar Carlsson"
  description: "ISC Kea"
  company: ""
  license: license (MIT)
  min_ansible_version: 2.2
  platforms:
    - name: FreeBSD
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - dhcp
dependencies: []
