# AppArmor configuration - important for Ubuntu 14.04
configure_apparmor: true

dhcp_interfaces: enp0s8

default_lease_time: 86400
max_lease_time: 86400

subnet:
  ip: 192.168.56.0
  mask: 255.255.255.0
  range:
    from: 192.168.56.100
    to: 192.168.56.200
  options:
     subnet-mask: 255.255.255.0
     broadcast-address: 192.168.56.255
     routers: 192.168.0.0
     domain-name-servers: 8.8.8.8
     domain-name: "\"fawcett.com\""
